
<MenuWidget>:
    
    canvas.before:
        Color:
            rgba: 0, 0, 0, .8

        Rectangle:
            size: self.size

    Label:
        text: root.parent.game_state
        pos_hint: {"center_x": .5, "center_y": .6}
        font_size: dp(50)

    Button:
        text: root.parent.action_button
        pos_hint: {"center_x": .5, "center_y": .4}
        size_hint: .2, .1
        background_normal: ""
        background_color: 1, .3, .4

        on_press: root.parent.start_game()